---
name: try docker push image

on:
    workflow_dispatch:
    push:

jobs:
    docker:
        runs-on: ubuntu-24.04
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: login to Docker Hub
          uses: opspresso/action-docker@master
          with:
            args: --docker
          env:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            BUILDX: "true"
