---
name: try docker push image

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/mavache

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern{{major}}.{{minor}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}




# jobs: #ma version
#   build:
#     runs-on: ubuntu-24.04
    
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v4

#     - name: Build Docker image
#       run: |
#         docker build -t ${{ vars.DOCKERHUB_USERNAME }}/mavache:${{ github.sha }} .

#     # - name: Set up Docker Buildx
#     #   uses: docker/setup-buildx-action@v2

#     - name: login to Docker Hub
#       # uses: opspresso/action-docker@master
#       run: docker login -u $USERNAME -p $TOKEN
#       env:
#         USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
#         PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#         TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

#     - name: Push Docker image
#       run: |
#         docker push ${{ vars.DOCKERHUB_USERNAME }}/mavache:${{ github.sha }}