---
name: try docker push image

on:
    workflow_dispatch:
    push:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-24.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: login to Docker Hub
      uses: opspresso/action-docker@master
      env:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ vars.DOCKERHUB_USERNAME }}/mavache:${{ github.sha }} .

    - name: Push Docker image
      run: |
        docker push ${{ vars.DOCKERHUB_USERNAME }}/mavache:${{ github.sha }}
